apiVersion: apps/v1
kind: Deployment
metadata:
  name: ps-app-ui
  namespace: tf
spec:
  selector:
    matchLabels:
      app: ps-app-ui
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ps-app-ui
    spec:
      containers:
        - name: ps-app-ui
          image: gcr.io/sylvan-bonbon-317613/ps-app-ui:0.0.0
          env:
            - name: ENV
              value: "prod"
