apiVersion: v1
kind: Service
metadata:
  labels:
    app: ps-app-ui
  name: ps-app-ui
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: ps-app-ui
